### PR TITLE
build Ansible 2.5.2

### PR DESCRIPTION
**Pull request by cyrilleverrier**

### CODE REVIEW

**Comment by ownport** [comment]
Thanks a lot for contribution

**Comment by cyrilleverrier** [comment]
@ownport Is the travis.yml outdated?

I connected my forked repo to Travis. The build fails: https://travis-ci.org/cyrilleverrier/portable-ansible/builds/378411230?utm_source=github_status&utm_medium=notification

```

**Comment by ownport** [comment]
@cyrilleverrier sorry for late response. Yes, you are right, .travis.yml file is outdated, removed fro repo. New release 2.5.2 was published and available for download https://github.com/ownport/portable-ansible/releases/tag/ansible-2.5.2

**Comment by cyrilleverrier** [comment]
@ownport  Thank you for the release

**Pull request merged**
